name: mfcc
sample_rate: 16000
n_mfcc: 13
n_mels: 128
width: 9
hop_length: 160
win_length: 400
n_fft: 400
use_delta: True
use_delta_delta: True
normalize: True
input_channels: 39
max_samples: 101 
min_samples: 95
pad_both_sides: False
constant_size: True