defaults:
  - encoder: 1d_cnn
  - optim: adam
  - conversion_method: mfcc

dataset: 'google_commands'
stemming: True
lematise: False
batch_size: 1
epoch_n_tasks: 200
max_epochs: 200
precision: 32
method: "reptile"
n_way: 5
k_shot: 1
augment: 'none'
embedding_dim: 128
return_features: False
noise_labels: 'unkown'
first_order: True

secrets:
  wandb_key: ''

hydra:
  run:
    dir: ./ # we only run multiruns to ensure we seperate each result
  sweep:
    dir: ./training_results_${noise_labels}_label/${dataset}/${method}/${encoder.name}/${conversion_method.name}/${n_way}_way/${k_shot}_shot/
